Mas19 re 66 interfejs import csv
lodz-university-of-technology-masi/Red pull request #16
Opened 2019-05-16 20:15 UTC by Piotr196

2019-05-16 20:29 UTC, JKalucki96 requested changes

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/test-details.js
> +    } else if (document.selection && document.selection.type != "Control") { //fixme do usuniecia (bylo tylko dla testow)
Czy jeszcze potrzebne?

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/test-details.js
>      console.log(query);
usuń console.log'a

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
> +    console.log('import');
usuń console.log'a

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
> +            console.log("ERROR : ", e);
powinien być console.error i bez `ERROR : `

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator-inc/modals-test.html
> +                            <div class="col">
czy potrzebny jest `<div class="col">`, czy można zmienić klase div'a wyżej z `row` na `column`?

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator-inc/modals-test.html
> +                            <div class="col">
czy potrzebny jest `<div class="col">`, czy można zmienić klase div'a wyżej z `row` na `column`?

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator-inc/modals-test.html
> +                            <div class="col">
czy potrzebny jest `<div class="col">`, czy można zmienić klase div'a wyżej z `row` na `column`?

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator.html
> +            <button class="btn btn-outline-success btn-block mt-5 mb-5" data-toggle="modal" data-target="#createTest"><i class="material-icons md-24">add_circle</i> Dodaj/importuj test</button>
za dluga linia kodu, rozbij na kilka

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/moderator-get.js
>          console.log(data);
usun console.log'a

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
>                  console.log("response: " + data);
usun console.loga'a. nie bedzie wtedy potrzeby argument `data`, więc tez mozesz go usunac

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/moderator-get.js
>                  console.log(index + " : " + value.id + value.firstName + value.lastName);
usun console.log'a

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/moderator-get.js
>          console.log(data);
usun console.log'a

2019-05-16 20:29 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator-inc/modals-test.html
> +                                <button class="btn btn-outline-primary mr-3" type="button" onclick="importTestFromCSV()">Importuj z pliku CSV</button>
za dluga linia kodu. rozbij na kilka

2019-05-16 21:42 UTC, Piotr196 commented on red-app/src/main/resources/templates/moderator-inc/modals-test.html
> +                            <div class="col">
Pod container powinno być najpierw row, a dopiero pod row może być col

2019-05-16 23:05 UTC, JKalucki96 requested changes

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
>              success: function (data) {
`data` nie jest uzywane, wiec mozesz usunac

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/moderator-search.js
> +        //console.log(e.pageX + "," + e.pageY + selectedText);
usun zakomentowany kod

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/moderator-search.js
> +    $(document).on("click",function(){
mozesz uzyc `.click(function (){ ` zamiast `.on("click",function(){`

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/moderator-search.js
> +                console.log(e);
`console.error` zamiast log'a

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/js/moderator-search.js
> +                console.log(e);
`console.error()` zamiast log'a

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
> +    console.log($('#'+ form.id).prop('files')[0])
usuń console.log'a i `form` jesli nie jest uzywany

2019-05-16 23:05 UTC, JKalucki96 commented on red-app/src/main/resources/templates/moderator.html
> +            <button class="btn btn-outline-success btn-block mt-5 mb-5" data-toggle="modal" data-target="#createTest" onclick="resetMessages()"><i class="material-icons md-24">add_circle</i> Dodaj/im
rozbij tą linijke na kilka, jest za dluga

2019-05-17 09:57 UTC, Piotr196 commented on red-app/src/main/resources/static/moderator-inc/mod-test.js
> +    console.log($('#'+ form.id).prop('files')[0])
zostawiłem dla osoby robiącej logike importu zeby komus bylo latwiej

2019-05-17 10:04 UTC, JKalucki96 approved these changes

2019-05-17 10:05 UTC, merged